#! /bin/sh

if [ -n "$VISUAL" ]; then
    alias vim='$VISUAL'
fi

alias ls='eza --group-directories-first'

# some more ls aliases
alias open="xdg-open"

#random Aliases
alias pianobar="pianobar | tee ~/.piano_lines.out"
alias update-altc='bfs ~/ -type d -nohidden > ~/.bfs.cache'

alias cat="batcat"
