#! /bin/bash


# set -o xtrace
set -e

MY_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
OLD_FILES="$HOME/oldfiles"


linkfile()
{
    SRCFILE="$MY_DIR/$1"
    if [ "x" = "x$2" ]; then
        DESTFILE=".$1"
    else
        DESTFILE="$2"
    fi

    if [ -L "$HOME/$DESTFILE" ]; then
        echo "$DESTFILE symlink exists. Good!"
        return 0
    elif [ -e "$HOME/$DESTFILE" ]; then
        if [ ! -e "$OLD_FILES/$DESTFILE" ]; then
            echo "Moving existing file too $OLD_FILES"
            mv -n "$HOME/$DESTFILE" "$OLD_FILES"
        else
            echo "ERROR: Failed to copy, file likely already exists in destination"
            exit 1
        fi
    fi

    ln -s "$SRCFILE" "$HOME/$DESTFILE"
}


# MAIN
cd "$MY_DIR"

mkdir -p "$OLD_FILES"
mkdir -p ~/.config
mkdir -p ~/tmp

linkfile gitconfig
linkfile git_template
linkfile gitignore_global

git submodule update --init --recursive

linkfile zshrc
linkfile profile
linkfile bashrc
linkfile vim
linkfile vimrc
linkfile gvimrc
linkfile nvim .config/nvim
linkfile xinitrc
linkfile Xresources
linkfile zprofile
linkfile xprofile
linkfile bspwm .config/bspwm
linkfile sxhkd .config/sxhkd
linkfile weechat .config/weechat
linkfile pianobar .config/pianobar
linkfile Scripts Scripts
linkfile tmux.conf

. $MY_DIR/install-packages.sh

exit 0
