#! /bin/bash
# scalerc configuration variables
# OPTIONAL BUILD_ROOT forces build to run make from $BUILD_ROOT
BUILDVM_HOSTNAME="buildvm"
COV_DIR="/local/cov"
GIT_ROOT="$HOME/git/scale-product" # on dev pc
DOORBELL='tput bel; sleep 1; tput bel'
TIMEOUT=10
END_CMD="$DOORBELL"
LOG_CMD="less -RN"
SCQAD_DIR="$SRC_ROOT/daemons/scqad"
TESTBEDS="mysql -B --disable-column-names -ureadonly -preadonly -h builddb.lab.local -e \"select testbed from claims where username = '$SCREWI_USER'\" re_ci 2> /dev/null | sed 's/\\>/-01.lab.local/g' | uniq"
BRANCH="sb_drsd"
PHAB_PROJECT="drsd"
GIT_USER="jlusby"

export SCREWI_USER="jlusby"
export SRC_ROOT="/local/scale-product" # on buildvm

# Set build flags
export MAKEFLAGS="-j $(($(nproc) - 1))"
# unset MAKEFLAGS

export TRACE_FLAGS=--coverage
# unset TRACE_FLAGS

export BUILD_TYPE=debug
# export BUILD_TYPE=opt

export BUILD_SCQAD_CASES=0
# unset BUILD_SCQAD_CASES

export ENABLE_BUILD_TIMER=1
# unset ENABLE_BUILD_TIMER

export NOCHECKSUMTEST=1
# unset NOCHECKSUMTEST

export V=2

export NORECURSION=1
unset NORECURSION

# export GCOV_PREFIX_STRIP=1
# export GCOV_PREFIX="$SRC_ROOT"

# export CCACHE_PREFIX="bear -a -o ~/compile_commands.json"
# unset CCACHE_PREFIX

# export CCACHE_LOGFILE=/tmp/ccache.debug
# unset CCACHE_LOGFILE

# export CCACHE_RECACHE=1

export GTEST_COLOR=1

export NO_UI=1
export GIT_CHANGED_BASE="origin/sb_drsd"
