#! /bin/sh

pathmunge() {
    if ! echo "$PATH" | grep -E -q "(^|:)$1($|:)"; then
        if [ "$2" = "after" ]; then
            PATH=$PATH:$1
        else
            PATH=$1:$PATH
        fi
    fi
}

export SSH_AUTH_SOCK=~/.1password/agent.sock

export PROFILE_SOURCED="true"

export HISTFILE=~/.history
export HISTSIZE=10000

pathmunge "$HOME/.ccache/bin"
pathmunge "$HOME/git/scwut/jlusby"
pathmunge "$HOME/.node_modules_global/bin"
pathmunge "/snap/bin"

if hash nvim 2>/dev/null; then
    export VISUAL="nvim"
elif hash vim 2>/dev/null; then
    export VISUAL="vim"
else
    export VISUAL="vi"
fi
export EDITOR=$VISUAL

if [ "$VISUAL" = "nvim" ]; then
    export VIMCONFIG=~/.config/nvim
    export VIMDATA=~/.local/share/nvim
else
    export VIMCONFIG=~/.vim
    export VIMDATA=~/.vim
fi

# colorful man pages
export LESS_TERMCAP_mb=$'\E[31m'
export LESS_TERMCAP_md=$'\E[31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[1;40;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[32m'

export XDG_CONFIG_HOME="$HOME/.config"

# if hash keychain >/dev/null 2>&1; then
#     eval "$(keychain --eval --quiet scale_computing2016_id_rsa.jane id_rsa id_ed25519 build_dsa build_rsa >/dev/null 2>&1)"
# fi

[ -n "$XTERM_VERSION" ] && transset-df .9 -a >/dev/null

FZF_DIR="$HOME/.fzf/bin/"
if [ -d $FZF_DIR ] || hash fzf; then
    # export FZF_DEFAULT_OPTS="--reverse --height 40%"
    export FZF_DEFAULT_OPTS="--height 40% --reverse --ansi --preview-window 'right:60%' --preview 'bat --color=always --style=header,grid --line-range :300 {}'"
    if hash rg 2>/dev/null; then
        export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden -g "!{.git,node_modules}/*" 2> /dev/null'
    fi
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    # If current selection is a text file shows its content,
    # if it's a directory shows its content, the rest is ignored
    export FZF_CTRL_T_OPTS="--select-1 --exit-0 --no-height --preview-window wrap --preview '
    if [[ -f {} ]]; then
        file --mime {} | grep -q \"text\/.*;\" && bat --color \"always\" {} || (tput setaf 1; file --mime {})
    elif [[ -d {} ]]; then
        exa --long --color=always {}
    else;
        tput setaf 1; echo Something went wrong!
    fi'"

    export FZF_CTRL_T_OPTS="--select-1 --exit-0"
    if hash bfs 2>/dev/null; then
        export FZF_ALT_C_COMMAND="bfs . -type d -nohidden 2> /dev/null"
    fi

    # export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
    export FZF_ALT_C_OPTS="--preview 'exa --tree --color=always {} | head -200'"
fi

export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"

pathmunge "$GOBIN"
pathmunge "$HOME/.cargo/bin"
pathmunge "$HOME/.local/bin"
pathmunge "$HOME/Scripts"

# export RUSTC_WRAPPER=sccache
# export SCCACHE_CACHE_SIZE="100G"
# export RUSTFLAGS="-C link-arg=-fuse-ld=lld"
# export WORKSPACE_RUSTC=clippy-driver

export BAT_CONFIG_PATH="$HOME/.batrc"

# Nix package manager config
if [ -e /home/jlusby/.nix-profile/etc/profile.d/nix.sh ]; then
    . /home/jlusby/.nix-profile/etc/profile.d/nix.sh
fi # added by Nix installer
export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive
