#! /bin/sh

export PROFILE_SOURCED="true"

export HISTFILE=~/.history
export HISTSIZE=10000

export PATH="$HOME/.ccache/bin:$PATH"
export PATH="$HOME/Scripts:$PATH"

if hash nvim 2>/dev/null; then
    export VISUAL="nvim"
elif hash vim 2>/dev/null; then
    export VISUAL="vim"
else
    export VISUAL="vi"
fi
export EDITOR=$VISUAL

if [ "$VISUAL" = "nvim" ]; then
    export VIMCONFIG=~/.config/nvim
    export VIMDATA=~/.local/share/nvim
else
    export VIMCONFIG=~/.vim
    export VIMDATA=~/.vim
fi

# colorful man pages
export LESS_TERMCAP_mb=$'\E[31m'
export LESS_TERMCAP_md=$'\E[31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[1;40;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[32m'

export XDG_CONFIG_HOME="$HOME/.config"

if hash keychain >/dev/null 2>&1; then
    eval "$(keychain --eval --quiet scale_computing2016_id_rsa.jane id_rsa id_ed25519 build_dsa build_rsa >/dev/null 2>&1)"
fi

[ -n "$XTERM_VERSION" ] && transset-df .9 -a >/dev/null

FZF_DIR="$HOME/.fzf/bin/"
if [ -d $FZF_DIR ] || hash fzf; then
    export PATH=$PATH:$FZF_DIR
    export FZF_DEFAULT_OPTS="--reverse --height 40%"
    if hash rg 2>/dev/null; then
        export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden -g "!{.git,node_modules}/*" 2> /dev/null'
    fi
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_CTRL_T_OPTS="--select-1 --exit-0"
    if hash bfs 2>/dev/null; then
        export FZF_ALT_C_COMMAND="bfs . -type d -nohidden 2> /dev/null"
    fi
    export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
fi

export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOBIN"
