#! /bin/sh
# exec i3 -V >> ~/.i3/i3log 2>&1

export BSPWM_SOCKET="/tmp/bspwm-socket"
export PANEL_FIFO="/tmp/panel-fifo"
export PANEL_HEIGHT=18

unclutter &
# /usr/bin/xscreensaver -no-splash &
xrdb ~/.Xresources
