#! /bin/bash

# shellcheck disable=SC1090
. ~/.scalerc

if [ "x" == "x$1" ]; then
    FULL_PATH="$(find "$GIT_ROOT" -type f -name "*UnitTest.cpp" | sort -u | fzf --select-1 --exit-0 --multi)"
else
    FULL_PATH=$1
fi

FILE_BASE=$(basename "$FULL_PATH")
without_ext=${FILE_BASE%.*}
common=${without_ext%%UnitTest}

{
    flock -x 3 || exit 1
    scunit "$common" || exit 1

    echo "coverage report"
    gcovcheck --vimgrep "$FULL_PATH"
} 3>/tmp/rscmake.lock | convertToPwd
