#! /bin/bash

# sc_build_root="$HOME/.scalerc"
# . $sc_build_root
# scmake $@ # | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
# cat $HOME/Scripts/lastbuild | sed -r "s/^\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"

#!/usr/bin/env bash

BUILDLOG="/tmp/lastbuild"

if [ -f $BUILDLOG ]; then
    tail -f -n +1 "$BUILDLOG" &# start tailing in the background
    while [[ -f $BUILDLOG ]]; do sleep 0.1; done # periodically check if target still exists
    kill $! 2>/dev/null || :                     # kill tailing process, ignoring errors if already dead
else
    rscmake
fi
