#! /bin/bash

sc_build_root="$HOME/.scalerc"
if [ -f "$sc_build_root" ]; then
    # shellcheck source=/home/jlusby/.scalerc
    . "$sc_build_root"
else
    exit 1
fi

BUILDLOG="/tmp/rscmake.log"
TARGET="all"
DIRNAME="$GIT_ROOT"

if [ "x$1" != "x" ]; then
    if [ -f "$1" ]; then
        DIRNAME="$(dirname "$1")"
        BASENAME="$(basename "$1")"
        TARGET="$(targetdir)/${BASENAME%.*}.o"
    fi
fi

if [ "$TARGET" != "all" ]; then
    MBUILDLOG="/dev/null"
else
    MBUILDLOG=$BUILDLOG
fi

cd "$DIRNAME" || exit 1

if [ "$TARGET" == "all" ]; then

    {
        flock -x 3 || exit 1
        LAST_FILE=""
        for file in $(git ls-files --exclude-standard --others --modified | xargs realpath); do
            if [ "x$LAST_FILE" = "x" ]; then
                LAST_FILE=$(dirname "$file")
            else
                LAST_FILE=$(printf "%s\\n%s\\n" "$LAST_FILE" "$file" | sed -e 'N;s/^\(.*\).*\n\1.*$/\1/')
            fi
        done

        if [ ! -f "$LAST_FILE" ]; then
            if [ ! -d "$LAST_FILE" ]; then
                LAST_FILE=$(dirname "$LAST_FILE")
            fi
            cd "$LAST_FILE" || exit 1
        fi
    } 3>/tmp/scgsync.lock

    {
        echo "Attmpting exclusive acquire on rscmake lock"
        flock -x 4 || exit 1
        echo "Acquired lock"
        scmake 2>&1 | convertToPwd
    } 4>/tmp/rscmake.lock
else
    {
        echo "Attmpting shared acquire on rscmake lock"
        flock -s 4 || exit 1
        echo "Acquired lock"
        time scmake "$TARGET" 2>&1 | convertToPwd
    } 4>/tmp/rscmake.lock

fi

exit $?
