#! /bin/python3

import fileinput
import argparse

parser = argparse.ArgumentParser(description='Manually sort files into different directories')
parser.add_argument('-d', '--dest-directories', nargs='+', required=True, help='directories for files to be placed into while sorting')
parser.add_argument('-r', '--randomize', action='store_true', help='randomize the order in which files are presented for sorting')
print( parser.parse_args() )

for line in fileinput.input('-'):
    print(line.rstrip(),end='')
    print()
